# Generated by Django 4.1.7 on 2023-02-19 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=200)),
                ('project_number', models.CharField(max_length=20)),
                ('acquisition_date', models.DateTimeField()),
                ('number_3l_code', models.CharField(max_length=3)),
                ('project_deal_type_id', models.CharField(max_length=20)),
                ('project_group_id', models.CharField(max_length=20)),
                ('project_status_id', models.CharField(max_length=20)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WTGs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('WTG_number', models.CharField(max_length=200)),
                ('WTG_Type_id', models.CharField(max_length=20)),
                ('Region_id', models.CharField(max_length=40)),
                ('kW', models.IntegerField()),
                ('hub', models.IntegerField()),
                ('rotor', models.IntegerField()),
                ('altitude', models.IntegerField(null=True)),
                ('COD', models.DateTimeField()),
                ('zip_code', models.IntegerField()),
                ('WGS_84_north', models.FloatField()),
                ('WGS_84_east', models.FloatField()),
                ('gauss_krueger_zone', models.IntegerField()),
                ('gauss_krueger_north', models.FloatField()),
                ('gauss_krueger_east', models.FloatField()),
                ('town_id', models.CharField(max_length=40)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_app.projects')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
