# Generated by Django 4.1.7 on 2023-02-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='WTGs',
            new_name='WTG',
        ),
    ]
