# Generated by Django 4.1.7 on 2023-02-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_rename_projects_project_rename_wtgs_wtg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
