# Generated by Django 4.1.7 on 2023-02-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='number_3l_code',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
